name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    name: Elixir build and test
    steps:

    - uses: actions/checkout@v2

    - uses: erlef/setup-beam@v1
      with:
        version-type: strict
        version-file: .tool-versions

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test